name: App web analisis de texto

on: [push]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: actions/checkout@v3
      - name: Instalar librerias
        run: |
          pip install -r requirements.txt
      - name: Correr formateo de codigo
        run: |
          pylint src
          flake8 src
  pruebas:
    runs-on: ubuntu-latest
    name: pruebas
    steps:
      - uses: actions/checkout@v3
      - name: Instalar librerias
        run: |
          pip install -r requirements.txt
      - name: Correr pruebas automatizadas
        run: |
          pytest tests --cov=src --cov-report=term-missing --cov-fail-under=10
